export const textAreaComment = 'textarea';
export const buttonSubmit = 'button[type="submit"]';
export const textErrorCommentSpanish = 'Reintentar';
export const buttonErrorComment = `button[text()="Reintentar"]`;
export const buttonLike = 'svg[aria-label="Like"]';
export const buttonFollowBackFromPost = "//button[text()='Follow Back']";
export const buttonFollowFromPost = "//button[text()='Follow']";
export const buttonSavePost = 'svg[aria-label="Save"]';
export const buttonFollowingFromPost = 'button[class="sqdOP yWX7d     _8A5w5    "]';
export const buttonUnfollow = 'button[class="aOOlW -Cab_   "]';
